### ISSUE TITLE
sit-wt_02_run-test　実行時にエラーとなる

### ISSUE THREAD

**Issue by ibuzu** [sitoolkit/sit-tester-archetype#1]
クイックスタートにて「Ecilipseで実行」に沿った動作を行いましたが、正常に実行することができません。

実行結果：
開始URL(=input.html)をオープンします
→
ファイルが見つかりませんでした
/C:/pleiades/workspace/sit-wt/input.html にはファイルが見つかりませんでした。

環境：firefox version:39.0

ログの一部抜粋：
Loading XML bean definitions from class path resource [sit-wt-conf.xml]
Refreshing org.springframework.context.support.GenericApplicationContext@282003e1: startup date [Sun Jul 12 11:18:52 JST 2015]; root of context hierarchy
Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@2f217633: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,debugSupport,ELSupport,locator,operationLog,pageItemSpec,pageSpecConverter,elementPositionSupport,seleniumDialogScreenshotSupport,seleniumTestScript,seleniumTestScriptConverter,testClassGenerator,current,testScript,testScriptCatalog,testScriptConvertUtils,repo,pm,dm,operationConverter,tester,drawLineOperation,clickOperation,inputOperation,keyOperation,chooseOperation,dialogOperation,openOperation,selectOperation,verifyOperation,waitOperation,switchWindowOperation,switchFrameOperation,storeOperation,storeElementIndexOperation,gotoOperation,execOperation,includeOperation,seleniumIdeCommandMap,pageSpecConverterMap,seleniumFirefoxDriver,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
操作ログ出力ディレクトリを作成しました。C:\pleiades\workspace\sit-wt\target\opelog_20150712111853
テストスクリプトをロードします。src/test/resources/testscript/ExcelTestScript.xlsx, TestScript
Excelファイルを読み込みます。C:\pleiades\workspace\sit-wt\src\test\resources\testscript\ExcelTestScript.xlsx
シート[TestScript]内の表データを18行読み込みました。
設計書定義を読み込みます。
XMLを読み込みます。file:/C:/pleiades/workspace/sit-wt/target/classes/documentMapping.xml
設計書定義を読み込みました。{testScript=org.sitoolkit.core.infra.repository.schema.Table@2e140e59, pageItemSpec=org.sitoolkit.core.infra.repository.schema.Table@49a71302}
Excelファイルを読み込みます。C:\pleiades\workspace\sit-wt\src\test\resources\testscript\ExcelTestScript.xlsx
シート[TestScript]内の表データを18行読み込みました。
ケース001を実行します
開始URL(=input.html)をオープンします
スクリーンショットを取得しました C:\pleiades\workspace\sit-wt\target\opelog_20150712111853\img\ExcelTestScript.xlsx_001_1_開始URL_後.png
スクリーンショットを取得しました C:\pleiades\workspace\sit-wt\target\opelog_20150712111853\img\ExcelTestScript.xlsx_001_2_名前_テスト実施が異常終了.png
Unable to locate element: {"method":"id","selector":"name"}
Command duration or timeout: 3.06 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'xxxxxxxx', ip: 'xxx.xxx.xxx.xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=39.0, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

**Comment by ykuwahara** [comment]
SIT-WTが現在使っているSelenium WebDriver 2.46.0が、Firefox 39.0をサポートしていないためと思われます。Firefoxを38.05かそれ以前のものに変えて試していただけますか。

**Comment by ibuzu** [comment]
回答ありがとうございます。
Firefoxを38.05にして、sit-wt_a0_run-demoを実行したところ、問題なく動作しました。
ありがとうございます。
